### ISSUE TITLE
LED (Neopixel) missing diagram/documentation

### ISSUE THREAD

**Issue by noelportugal** [ibmtjbot/tjbot#1]
Can you add a fritzing diagram to show the connection to the Neopixel LED? After some digging I found out the following:

RPI 5V -- diode -- LED V
RPI GND -- LED GND
RPI 18   -- LED Data In

Thanks!

**Comment by maryamashoori** [comment]
RPI 3.3V -- LED V
RPI GND -- LED GND
RPI 18 -- LED Data In

Fritzing diagrams and detailed wiring instructions are available on http://www.instructables.com/id/Use-Your-Voice-to-Control-a-Light-With-Watson/ 

I added links of wiring to the hardware section! :-)
