### ISSUE TITLE
STT other language - recipes-speech_to_text

### ISSUE THREAD

**Issue by jersonjunior** [ibmtjbot/tjbot#10]
I would like to use the Portuguese language, how do I change from US to PT-BR?
, how do I change from US to PT-BR?

**Comment by victordibia** [comment]
Hi Jersonjunior,

STT Supports several languages, Brazillian portugese included. To change from the default language (US) to portugese, you will need to update the model parameter within your createRecognizerStream method.

var recognizeparams = {
  content_type: 'audio/l16; rate=44100; channels=2',
  model: 'pt-BR_BroadbandModel'   // Change your language model here
}

var textStream = micInputStream.pipe(
    speech_to_text.createRecognizeStream(recognizeparams)
);

-V.

**Comment by jersonjunior** [comment]
Thank you, very fast!
