### ISSUE TITLE
Why use Google DNS if there is Quad9

### ISSUE THREAD

**Issue by paulbauriegel** [ibmtjbot/tjbot#100]
The start script asks for the installation of Google DNS. Why does the script not propose the use of the Quad9 DNS server: 9.9.9.9

**Comment by jweisz** [comment]
Never heard of it. What are the advantages of using it over Google?

**Comment by paulbauriegel** [comment]
It's privacy-friendly alternative to Google DNS. Initiated by IBM, among others.

**Comment by jweisz** [comment]
Feel free to submit a PR and I'll accept. ;)

**Comment by jweisz** [comment]
I just added this to TJBot 1.4.1. Thanks for the suggestion.
