### ISSUE TITLE
conversationjs -- error : linux-arm-57 missing ... have tried multiple versions of node and re- npm installing, always same error

### ISSUE THREAD

**Issue by Dswag** [ibmtjbot/tjbot#103]
### **I received this error when I try to `sudo node conversation.js`** 

`## There is an issue with node-fibers ##
/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/bin/linux-arm-57/fibers.node is missing.

Try running this to fix the issue: /usr/bin/node /home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/build
Error: Cannot find module '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/bin/linux-arm-57/fibers'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/fibers.js:13:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/fibers.js:22
throw new Error('Missing binary. See message above.');
^

Error: Missing binary. See message above.
    at Object.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/fibers.js:22:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/asyncawait/src/fibers.js:1:75)
    at Module._compile (module.js:652:30)
`

### **I'm not sure if this has anything to do with it, but this is what I get when I use npm install to get the dependencies again and again**

`rm -rf node_modules
pi@william:~/Desktop/cleantjbot/recipes/conversation $ npm install

> fibers@2.0.2 install /home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/build'
Installed in `/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/fibers/bin/linux-arm-51/fibers.node`

> pigpio@0.4.0 install /home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/pigpio
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/pigpio/build'
  CXX(target) Release/obj.target/pigpio/src/pigpio.o
  SOLINK_MODULE(target) Release/obj.target/pigpio.node
  COPY Release/pigpio.node
make: Leaving directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/pigpio/build'

> rpi-ws281x-native@0.8.2 install /home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/rpi-ws281x-native
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/rpi-ws281x-native/build'
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/ws2811.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/pwm.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/dma.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/mailbox.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/board_info.o
  AR(target) Release/obj.target/rpi_libws2811.a
  COPY Release/rpi_libws2811.a
  CXX(target) Release/obj.target/rpi_ws281x/src/rpi-ws281x.o
../src/rpi-ws281x.cc: In function ‘void init(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/rpi-ws281x.cc:100:38: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symFreq)) {
                                      ^
In file included from /home/pi/.node-gyp/7.10.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/7.10.1/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/7.10.1/include/node/v8.h:3168:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/7.10.1/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:104:40: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symDmaNum)) {
                                        ^
In file included from /home/pi/.node-gyp/7.10.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/7.10.1/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/7.10.1/include/node/v8.h:3168:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/7.10.1/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:108:41: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symGpioPin)) {
                                         ^
In file included from /home/pi/.node-gyp/7.10.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/7.10.1/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/7.10.1/include/node/v8.h:3168:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/7.10.1/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:112:40: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symInvert)) {
                                        ^
In file included from /home/pi/.node-gyp/7.10.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/7.10.1/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/7.10.1/include/node/v8.h:3168:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/7.10.1/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:116:44: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symBrightness)) {
                                            ^
In file included from /home/pi/.node-gyp/7.10.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/7.10.1/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/7.10.1/include/node/v8.h:3168:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/7.10.1/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/rpi_ws281x.node
  COPY Release/rpi_ws281x.node
  COPY ../lib/binding/rpi_ws281x.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/rpi-ws281x-native/build'

> sleep@5.2.3 install /home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/sleep
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make: Leaving directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/sleep/build'

> websocket@1.0.28 install /home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/websocket/build'
conversation@0.0.1 /home/pi/Desktop/cleantjbot/recipes/conversation
└─┬ tjbot@1.4.0 
  ├─┬ assert@1.4.1 
  │ └─┬ util@0.10.3 
  │   └── inherits@2.0.1 
  ├─┬ asyncawait@1.0.7 
  │ ├── bluebird@3.5.2 
  │ ├── fibers@2.0.2 
  │ └── lodash@4.17.11 
  ├── color-model@0.2.2 
  ├── colornames@1.1.1 
  ├── fifo@2.3.0 
  ├── mic@2.1.2 
  ├─┬ node-raspistill@0.0.11 
  │ ├─┬ image-type@3.0.0 
  │ │ └── file-type@4.4.0 
  │ └─┬ object.assign@4.1.0 
  │   ├── define-properties@1.1.3 
  │   ├── function-bind@1.1.1 
  │   ├── has-symbols@1.0.0 
  │   └── object-keys@1.0.12 
  ├─┬ object.pick@1.3.0 
  │ └── isobject@3.0.1 
  ├─┬ pigpio@0.4.0 
  │ ├── bindings@1.2.1 
  │ └── nan@2.4.0 
  ├── rpi-ws281x-native@0.8.2 
  ├── semaphore@1.1.0 
  ├─┬ sleep@5.2.3 
  │ └── nan@2.11.1 
  ├── sound-player@1.0.13 
  ├─┬ temp@0.8.3 
  │ ├── os-tmpdir@1.0.2 
  │ └── rimraf@2.2.8 
  ├─┬ watson-developer-cloud@3.11.1 
  │ ├── @types/csv-stringify@1.4.2 
  │ ├── @types/extend@3.0.0 
  │ ├── @types/file-type@5.2.1 
  │ ├── @types/is-stream@1.1.0 
  │ ├── @types/node@10.3.6 
  │ ├─┬ @types/request@2.47.1 
  │ │ ├── @types/caseless@0.12.1 
  │ │ ├── @types/form-data@2.2.1 
  │ │ └── @types/tough-cookie@2.3.3 
  │ ├── async@2.6.1 
  │ ├── buffer-from@1.1.1 
  │ ├─┬ csv-stringify@1.0.4 
  │ │ └── lodash.get@4.4.2 
  │ ├── extend@3.0.2 
  │ ├── file-type@7.7.1 
  │ ├── isstream@0.1.2 
  │ ├─┬ mime-types@2.1.20 
  │ │ └── mime-db@1.36.0 
  │ ├─┬ object.omit@3.0.0 
  │ │ └─┬ is-extendable@1.0.1 
  │ │   └── is-plain-object@2.0.4 
  │ ├─┬ request@2.87.0 
  │ │ ├── aws-sign2@0.7.0 
  │ │ ├── aws4@1.8.0 
  │ │ ├── caseless@0.12.0 
  │ │ ├─┬ combined-stream@1.0.7 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├─┬ form-data@2.3.2 
  │ │ │ ├── asynckit@0.4.0 
  │ │ │ └── combined-stream@1.0.6 
  │ │ ├─┬ har-validator@5.0.3 
  │ │ │ ├─┬ ajv@5.5.2 
  │ │ │ │ ├── co@4.6.0 
  │ │ │ │ ├── fast-deep-equal@1.1.0 
  │ │ │ │ ├── fast-json-stable-stringify@2.0.0 
  │ │ │ │ └── json-schema-traverse@0.3.1 
  │ │ │ └── har-schema@2.0.0 
  │ │ ├─┬ http-signature@1.2.0 
  │ │ │ ├── assert-plus@1.0.0 
  │ │ │ ├─┬ jsprim@1.4.1 
  │ │ │ │ ├── extsprintf@1.3.0 
  │ │ │ │ ├── json-schema@0.2.3 
  │ │ │ │ └─┬ verror@1.10.0 
  │ │ │ │   └── core-util-is@1.0.2 
  │ │ │ └─┬ sshpk@1.14.2 
  │ │ │   ├── asn1@0.2.4 
  │ │ │   ├── bcrypt-pbkdf@1.0.2 
  │ │ │   ├── dashdash@1.14.1 
  │ │ │   ├── ecc-jsbn@0.1.2 
  │ │ │   ├── getpass@0.1.7 
  │ │ │   ├── jsbn@0.1.1 
  │ │ │   ├── safer-buffer@2.1.2 
  │ │ │   └── tweetnacl@0.14.5 
  │ │ ├── is-typedarray@1.0.0 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├── oauth-sign@0.8.2 
  │ │ ├── performance-now@2.1.0 
  │ │ ├── qs@6.5.2 
  │ │ ├── safe-buffer@5.1.2 
  │ │ ├─┬ tough-cookie@2.3.4 
  │ │ │ └── punycode@1.4.1 
  │ │ ├── tunnel-agent@0.6.0 
  │ │ └── uuid@3.3.2 
  │ ├── vcap_services@0.3.4 
  │ └─┬ websocket@1.0.28 
  │   ├─┬ debug@2.6.9 
  │   │ └── ms@2.0.0 
  │   ├── nan@2.11.1 
  │   ├── typedarray-to-buffer@3.1.5 
  │   └── yaeti@0.0.6 
  └─┬ winston@2.4.4 
    ├── async@1.0.0 
    ├── colors@1.0.3 
    ├── cycle@1.0.3 
    ├── eyes@0.1.8 
    └── stack-trace@0.0.10 
`

**_I really appreciate the help, I have been trying for many weeks now to get TJ bot running and almost gave up but I'd figure I would give it one last shot._**

**Comment by Dswag** [comment]
Hi my operating system file shows version 9 (Stretch) and I'm running a Raspberry pi Model 3 B.

Thank you for the help!! That command actually resolved the linux arm issue. Now I seemed to have run into another problem after sudo node conversation.js: 

return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/sleep/build/Release/node_sleep.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/sleep/index.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:24:15)
    at Module._compile (module.js:652:30)


Any insight you could give me?

**Comment by Dswag** [comment]
Solved this issue by fixing node.

If anyone has this issue and wants me to elaborate on what I did I will help.

**Comment by Julianoe** [comment]
It's not a related thing directly to this specific software but we seem to have a similar problem, i'd be interested in a bit more detail on how you solved your problem if you don't mind. Thanks !

**Comment by mframos3** [comment]
@Dswag I have the same problem. How do I solve it? 
I've been having trouble with node versions in order to make TJBot work. Right now I'm using node v8.16 w/ npm v.6.4.1.
