### ISSUE TITLE
Clarify NeoPixel RGB LED size

### ISSUE THREAD

**Issue by jthub** [ibmtjbot/tjbot#11]
I'm pretty sure the NeoPixel RGB LED should be 8mm (measured the hole on a 3D printed head, and that seems to be the size the instructables link to) however the links on in github take you to 5mm LEDs.

It would be great to update the link text to indicate the required size explicitly, and update the links to point to the correct size.

**Comment by victordibia** [comment]
Hi @jthub 
You are right the 8mm LED is what we use.
Thanks pointing that out. The link on the sentiment recipe [README](https://github.com/ibmtjbot/tjbot/blob/master/recipes/sentiment_analysis/README.md) has now been updated.

Best.
Victor

**Comment by jthub** [comment]
It still looks like https://github.com/ibmtjbot/tjbot/blob/master/recipes/sentiment_analysis/README.md links to the 5mm LED. It would also be good to clarify in the link text, e.g. "NeoPixel 8mm RGB LED"

Similarly for the links on https://github.com/ibmtjbot/tjbot/blob/master/recipes/README.md

**Comment by maryamashoori** [comment]
Thanks, James. fixed.
