### ISSUE TITLE
problems with tj.see and tj.recognizeObjectsInPhoto 

### ISSUE THREAD

**Issue by winchenbach** [ibmtjbot/tjbot#110]
whenever i try to run tj.see (like in the conversation sample recipe) or have tjbot take a photo and then do recognizeObjectsInPhoto on it, I don't get a response from watson. The request eventually times out with: 

Unhandled rejection Error: connect ETIMEDOUT 54.209.159.70:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)

**Comment by winchenbach** [comment]
Well, this morning it just started working. Must have been a snafu with the Watson services that automagically fixed itself.

**Comment by jweisz** [comment]
Interesting. It does look like it was some kind of transient networking issue. Closing this issue since it resolved itself. :)
