### ISSUE TITLE
Removing/reinstalling node_modules in sentiment_analysis gives out ‘V8_DEPRECATED’; sentiment.js halts after line 105:48

### ISSUE THREAD

**Issue by ciptsrc** [ibmtjbot/tjbot#120]
I tried to use the tone-analyzer tool but it does not work. I triple-checked my credentials and account settings in bluemix and twitter, they are all fine. The two other recipes work very well with my credentials in setup config.js. 

The project looks to me as if it is no longer maintained. On a fresh install, I had to edit the config. js for all of the three skills manually, replacing username and password with apikey and url. At the bottom there is api_key used, which had to be edited manually to apikey.

Being aware that the tjbot is made for beginners, and I am a beginner too, it seems that the documentation is no longer accurate, and it is very easy to run in audio issues which I could solve for myself after many hours of research. I use an external sound card and the problem that it will be not set up properly in the tjbot although it is already well set up in the Raspberry OS still remains.
One has to either set up the SpeakerDeviceId manually in the respective ,js or manually edit in node_modules/tjbot/lib/tjbot.js for each recipe.

I want to show the tjbot to others, and explain how to set up, because most of the issues I can solve for myself, but with the sentiment_analyzer skill it won´t work. I add here the output I got from reinstalling the skill. Any help I would greatly appreciate.

> pigpio@0.4.0 install /home/pi/tjbot/recipes/sentiment_analysis/node_modules/pigpio
> node-gyp rebuild

make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/pigpio/build“ wird betreten
  CXX(target) Release/obj.target/pigpio/src/pigpio.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/pigpio.cc:3:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:64: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/pigpio.cc:3:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3165:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/pigpio.node
  COPY Release/pigpio.node
make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/pigpio/build“ wird verlassen

> rpi-ws281x-native@0.8.2 install /home/pi/tjbot/recipes/sentiment_analysis/node_modules/rpi-ws281x-native
> node-gyp rebuild

make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/rpi-ws281x-native/build“ wird betreten
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/ws2811.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/pwm.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/dma.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/mailbox.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/board_info.o
  AR(target) Release/obj.target/rpi_libws2811.a
  COPY Release/rpi_libws2811.a
  CXX(target) Release/obj.target/rpi_ws281x/src/rpi-ws281x.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/rpi-ws281x.cc:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:64: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
                                                                ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3165:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc: In function ‘void init(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/rpi-ws281x.cc:100:38: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symFreq)) {
                                      ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3385:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:104:40: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symDmaNum)) {
                                        ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3385:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:108:41: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symGpioPin)) {
                                         ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3385:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:112:40: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symInvert)) {
                                        ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3385:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:116:44: warning: ‘bool v8::Object::HasOwnProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     if(config->HasOwnProperty(symBrightness)) {
                                            ^
In file included from /home/pi/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:47,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.node-gyp/9.11.2/include/node/v8.h:3385:43: note: declared here
   V8_DEPRECATED("Use maybe version", bool HasOwnProperty(Local<String> key));
                                           ^
/home/pi/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/rpi_ws281x.node
  COPY Release/rpi_ws281x.node
  COPY ../lib/binding/rpi_ws281x.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/rpi-ws281x-native/build“ wird verlassen

> sleep@5.2.3 install /home/pi/tjbot/recipes/sentiment_analysis/node_modules/sleep
> node-gyp rebuild

make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/sleep/build“ wird betreten
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/sleep/build“ wird verlassen

> websocket@1.0.28 install /home/pi/tjbot/recipes/sentiment_analysis/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/websocket/build“ wird betreten
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Verzeichnis „/home/pi/tjbot/recipes/sentiment_analysis/node_modules/websocket/build“ wird verlassen
added 111 packages from 164 contributors and audited 201 packages in 108.04s
found 0 vulnerabilities

**Comment by jweisz** [comment]
I'm not sure about the pigpio errors, but the sentiment analysis issue has been potentially fixed in #125 and will be tested & merged in later this week.

Apologies that it's taking a long time to get these issues fixed, but I was on leave at the end of last year. I'm also the only one maintaining this code, and this isn't even part of my day job. 😬 

Closing the issue, but please re-open if you have more questions.
