### ISSUE TITLE
TJBot LED test passing, hearing my commands, not changing color

### ISSUE THREAD

**Issue by daviadenisco** [ibmtjbot/tjbot#123]
The LED wiring is definitely hooked up correctly, I've check, double checked, triple checked, and had someone else do the same. All LED tests are passing. My commands are being received and are showing up in the terminal. But the light doesn't change color when I speak the command.

**Comment by daviadenisco** [comment]
Hahaha Thanks, JW! Appreciate the suggestions. I checked it out and turns out it was an issue in the code. It's working as it should now!

**Comment by jweisz** [comment]
I'm glad you figured it out! Closing this issue. 😉
