### ISSUE TITLE
crash after several successful runs

### ISSUE THREAD

**Issue by chentong319** [ibmtjbot/tjbot#128]
I followed the instructions in tjbot and tried the speach-to-text. It ran successfully. However, after about 10 runs, I got error message at initialization. After the crash, I could not find my / . I had to reboot my system by unplugging the power, and the file system came back again. But "sudo node stt.js" would crash. I have to rerun the set up (bootstrap and npm install) and sometimes my stt.js became empty. Then I can run my TJBot again.

**Comment by jweisz** [comment]
I'm not sure why this would be happening. Could it be a bad SD card?  It doesn't seem like the TJBot software would cause the RPi to crash in the way you describe. Please re-open the issue if you think this is a tjbot-specific problem.
