### ISSUE TITLE
Suggestion: Support For Newer Version of Node/JavaScript

### ISSUE THREAD

**Issue by Mattemyo** [ibmtjbot/tjbot#132]
As a frontend developer working with JavaScript daily, I think it would be really nice to be able to write scripts for TJ Bot with fancy ES6 syntax. I believe the easiest way of making this work would be to use [Babel](https://babeljs.io/).

What is the status on this?

**Comment by jweisz** [comment]
Is there something we would need to change with the TJBot library to enable you to do this?

**Comment by Mattemyo** [comment]
I would suggest creating a recipe/example that uses `babel-cli` with certain configurations. What do you think?

**Comment by jweisz** [comment]
I never got the chance to explore this, so I'm going to close the issue. If you would still like to pursue it, please go ahead and explore.
