### ISSUE TITLE
Apps.twitter.com has been sunset

### ISSUE THREAD

**Issue by ryanomor** [ibmtjbot/tjbot#136]
I was reading through the `sentiment_analysis` recipe and noticed that the link to get the consumer key, consumer secret, access token key, and access token secret has been sunset by Twitter.
How should we get these keys/secrets now?

**Comment by maryamashoori** [comment]
Did you try https://developer.twitter.com/en/apps?

**Comment by ryanomor** [comment]
I have, but not sure how to go about getting the keys/secrets from there.

**Comment by jweisz** [comment]
If you figure this out, I'd appreciate a pull request to update the recipe for Twitter's new API. ;)

**Comment by lpoon22** [comment]
I'm stuck here too. Was this ever figured out? @maryamashoori

**Comment by jweisz** [comment]
Not sure if you figured this out already, but there is a "Keys and Tokens" section when viewing the app details. Closing this issue, but feel free to re-open if you still have questions.
