### ISSUE TITLE
TJ gets tongue-tied when conversation response includes output text array with empty members

### ISSUE THREAD

**Issue by jthub** [ibmtjbot/tjbot#14]
The output of the Conversation service includes a text array which can include empty text. When TJ encounters this kind of output and tries to send empty text to the text to speech service, it causes an error.

For example, the sample car workspace causes this issue.

**Comment by victordibia** [comment]
Nice catch!
thanks for contributing back!
looking forward to learning more about any other recipes you are building/experimenting with!
-V.
