### ISSUE TITLE
Adding bash scripts to test Watson AI services from TJBOT

### ISSUE THREAD

**Issue by mkhuthir** [ibmtjbot/tjbot#140]
It will be great if we have bash scripts that will allow us to test Watson AI services directly without using TJBOT Node.JS Library. This will help in troubleshooting issues.

**Comment by jweisz** [comment]
👍  great idea, please see my comments in the PR.

**Comment by mkhuthir** [comment]
Updated code as per our discussion and pushed it. Thanks
