### ISSUE TITLE
Error when i ask tjbot

### ISSUE THREAD

**Issue by sgsilva** [ibmtjbot/tjbot#154]
B, name of tjbot.
when i ask him i got erros.

`im a screwdriver. :
verbose: TJBot speaking with voice en-US_MichaelVoice
verbose: TJBot speaking: A robot walks into a bar. “What can I get you?” the bartender asks. “I need something to loosen up,” the robot replies. So the bartender serves him a screwdriver.
========= { filename: '/tmp/tjbot202011-1544-175a99s.t83z',
  gain: 100,
  debug: true,
  player: 'aplay',
  device: 'plughw:0,0' }

`

**Comment by jweisz** [comment]
Hi @sgsilva , I'm not sure I see the error above. It looks like the recipe worked correctly. What was the error?

**Comment by sgsilva** [comment]
i was solved, i chenge de apikey and work, thanl you friend!
