### ISSUE TITLE
TJbot cannot run with ibm-watson sdk

### ISSUE THREAD

**Issue by xulix** [ibmtjbot/tjbot#159]
As we need to run the TJbot with the Watson service from ICP4D, and at least need to use the self-signed certificate with the ssl disabled. But this kind of connection like 'BearerTokenAuthentication' is only supported by ibm-watson sdk, not watson-developer-cloud sdk.

ibm-watson sdk is working with node version 10+, then the tjbot will not work.

**Comment by jweisz** [comment]
Closing this issue as tjbot 2.0.0 now uses the latest ibm-watson SDK.
