### ISSUE TITLE
Does TJBot work on Raspbian 10 (Buster) on Raspberry Pi 3?

### ISSUE THREAD

**Issue by TheVinhLuong102** [ibmtjbot/tjbot#165]
I've used the standard bootstrap script `curl -sL http://ibm.biz/tjbot-bootstrap | sudo sh -` and found that Raspbian 10 (Buster) has been installed:

```
cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

When I run various hardware tests, there seem to be a lot of errors.

May I check if TJBot works for Buster, and if not then how can we get back to Jessie or Stretch?

Thank you very much!

**Comment by jweisz** [comment]
I think in theory it should but the code is pretty dated at this point and a lot of the dependencies haven't been updated in a long time. So, I wouldn't be surprised if it's not working at the moment. I'm working on an update to use the latest SDKs (IBM Watson, LED, etc.) but it's still a work in progress and isn't ready for public consumption yet. Please stay tuned. :)

**Comment by TheVinhLuong102** [comment]
Thank you in advance, @jweisz!

**Comment by jweisz** [comment]
Closing this issue as TJBot 2.0.0 should resolve all outstanding issues running on Buster.
