### ISSUE TITLE
Two recipes repo

### ISSUE THREAD

**Issue by bgbraga** [ibmtjbot/tjbot#17]
There is two recipes folders in ibmtjbot:

https://github.com/ibmtjbot/tjbot/tree/master/recipes
https://github.com/ibmtjbot/recipes

It is a little confuse. The code is different.

**Comment by victordibia** [comment]
Hi @bgbraga ,
Thanks for pointing that out.
The code is different because the recipes here - https://github.com/ibmtjbot/recipes - is based on an experimental [tjbot library](https://github.com/ibmtjbot/tjbotlib)  we are developing.

I have now updated the readme to reflect this.
-V.

**Comment by maryamashoori** [comment]
Just released TJBot v1.1.0 with a new library and documentation to make writing recipes even easier!
