### ISSUE TITLE
Upgrade node.js version on bootstrap script

### ISSUE THREAD

**Issue by robertoetcheverryr** [ibmtjbot/tjbot#178]
Hello,
I just ran the tjbot bootstrap on my tjbot (I inherited from a coworker, so now I'm fully updating it)
And noticed that it installs node.js v15 which is not supported. I am not a node.js dev so I do not know how difficult it would be to test the code against v16 and change the installation script, so I open this issue to see how feasible it is.

**Comment by jweisz** [comment]
Update needs to happen in `bootstrap.sh` lines 138-168

https://github.com/ibmtjbot/tjbot/blob/master/bootstrap/bootstrap.sh

**Comment by jweisz** [comment]
We accepted this PR:
https://github.com/ibmtjbot/tjbot/pull/225
