### ISSUE TITLE
Link to conversation flow instructions is broken

### ISSUE THREAD

**Issue by jthub** [ibmtjbot/tjbot#2]
The `Here is a step-by-step instructions to create a conversation flow.` link in the Creating a Conversation Flow section is broken on https://github.com/ibmtjbot/tjbot/tree/master/recipes/conversation

**Comment by victordibia** [comment]
Thanks a lot. fixed.
http://www.instructables.com/id/Build-a-Talking-Robot-With-Watson-and-Raspberry-Pi/#step6

**Comment by jthub** [comment]
Great, thanks very much!
