### ISSUE TITLE
Node conversation.js Issue

### ISSUE THREAD

**Issue by GaltresIT** [ibmtjbot/tjbot#24]
Hello

Just installed following your instructions and encountered this when I execute Node conversation.js

Please can you help please?

J
![tj](https://cloud.githubusercontent.com/assets/16475660/24336567/55f2ee08-1289-11e7-8f61-72ff58f729c5.png)

**Comment by cjnweb** [comment]
I am having the same issue.  Looks like the TJBot is not getting instantiated.  Not sure what I am missing to make that happen.

**Comment by jtmate09** [comment]
Hi cjnweb

At least I am not the only one! 

V.0 had no issues in this department.

**Comment by bgbraga** [comment]
@jweisz

**Comment by cjnweb** [comment]
Looks like TJBot is being instantiated but the robot.name is not defined anywhere.

**Comment by maryamashoori** [comment]
​We just updated the library. If you are seeing this error, please do the following:

$ cd tjbot/recipes/conversation

$ rm -r node_modules

$ npm install

$ sudo node conversation.js
This should solve the problem! :-)
