### ISSUE TITLE
Add new recipe for `conversation-watsonx`

### ISSUE THREAD

**Issue by jweisz** [ibmtjbot/tjbot#251]
We should implement a new recipe to demonstrate a conversational LLM experience with TJBot. Now that there are chat-tuned models available (e.g. `llama-2-70b-chat` and `granite-13b-chat-v1`), this should work well.

Also, use `langchain` to drive the conversation! 😄

**Comment by modcarroll** [comment]
The code for this is working - I'm just having trouble testing the hardware so I'll continue to work on that
