### ISSUE TITLE
Clean out outdated recipes

### ISSUE THREAD

**Issue by jweisz** [ibmtjbot/tjbot#268]
- remove translator recipe
- add to watsonx recipe
- use latest version of granite in the code
- in the readme use llama and mistral (have them update the prompt themselves in the code and provide samples in the readme)

**Comment by jweisz** [comment]
@modcarroll I forgot what we decided to do about `sentiment_analysis` -- either remove it or push the functionality into `conversation_watsonx`?

**Comment by modcarroll** [comment]
We decided to remove `sentiment_analysis` I believe. We could create a prompt template for it in `conversation_watsonx` though

**Comment by modcarroll** [comment]
And I am handling the removal of this in the latest PR where I add `conversation_watsonx`
