### ISSUE TITLE
Move API into Speech to Text recipe

### ISSUE THREAD

**Issue by modcarroll** [ibmtjbot/tjbot#269]
Call the STT service directly from the recipe instead of using .listen()

**Comment by modcarroll** [comment]
@jweisz the conversation recipes use .listen() so I need to add the STT API call directly in those as well, correct?

**Comment by modcarroll** [comment]
Or were we leaving STT/TTS as is in lib?

**Comment by jweisz** [comment]
STT & TTS will remain in tjbotlib since they are "core". `listen()` is how to invoke STT, which should (still) work in `node-tjbotlib` and does not currently work in `python-tjbotlib`.
