### ISSUE TITLE
Continuous Conversation

### ISSUE THREAD

**Issue by Leo-Dev** [ibmtjbot/tjbot#3]
Hi,

Would you please tell how to work with "continuous conversation" ?
I setup dialog with  "continuous conversation", It seems can not go to second dialog. 
I tested the dialog and it works on Web.

Please help.
 
Thank you.

**Comment by victordibia** [comment]
Hi @Leo-Dev ,
Thanks for pointing this out. The initial recipe was made simple to support simple intent matching.
You can pull the repo again, I'v added support for continuous conversation.
Look forward to seeing what you build with #tjbot!

V.

**Comment by Leo-Dev** [comment]
Great, it works, thanks very much!
