### ISSUE TITLE
Error connecting to speech_to_text

### ISSUE THREAD

**Issue by drewlahart** [ibmtjbot/tjbot#30]
When launching, errors look like this:

pi@raspberrypi:~/tjbot/recipes/speech_to_text $ sudo node stt.js
info: Hello from TJBot! My name is Watson.
I understand lots of colors.  You can tell me to shine my light a different color by saying 'turn the light red' or 'change the light to green' or 'turn the light off'.
**error: the speech_to_text service returned an error. type=error, isTrusted=false, _yaeti=true, , addEventListener=function _addEventListener(type, newListener) {
	var
		listenersType,
		i, listener;**

Then the command line gets into an endless loop. 

Bluemix Credentials are checked and double checked. Any suggestions would be appreciated. Thank you.

**Comment by victordibia** [comment]
Hi drew ...
In my experience, the above occurs if

- Your internet connection is down
- Your credentials are incorrect or you have reached your limit (I'd suggest creating a fresh credential pair and trying this).

V.

**Comment by drewlahart** [comment]
closing - was a bluemix issue. Thank you! Working well now.

**Comment by heanluen** [comment]
I am getting this error 80% of the time. another 20% is error: unable to retrieve TTS voices Error: Not Authorized

**Comment by christianmackin** [comment]
I am getting the same error. I have tried creating new creds. I can ping Google to show internet access. Is there any other way to test access to Watson? Any other ideas to figure out where the breakdown is?

**Comment by victordibia** [comment]
@christianmackin  .. what errors are you getting?
One simple check is to ensure you have not interchanged your username and password.
the password is the shorter value.
