### ISSUE TITLE
[rpi-ws281x-native] Could not verify raspberry-pi version.

### ISSUE THREAD

**Issue by divya2100** [ibmtjbot/tjbot#39]
Hi Team,

I am using speech to text recipe. When i try to use sudo node stt.js, I get the following error

[rpi-ws281x-native] Could not verify raspberry-pi version. If this is wrong and you are running this on a raspberry-pi, please file a bug-report at   https://github.com/beyondscreen/node-rpi-ws281x-native/issues
![image](https://cloud.githubusercontent.com/assets/28347724/25755800/00fc58f8-31e2-11e7-84d5-0909fd77dea8.png)

I created new instance for credentials for speech to text & also deleted any old services.
Could you please help in this regard

Thanks
Divya

**Comment by divya2100** [comment]
Just an update
1. Microphone is connected. I have tested it using
record -D plughw:1,0 test.wav & aplay test.wav.

2. LED is working. I used the following example from Adafruit to confirm
https://learn.adafruit.com/neopixels-on-raspberry-pi/software
I changed the no. of LEDs to 1 & used sudo python strandtest.py
This changed the color of the LEDs as desired.

But not sure why I am getting these errors
1. [rpi-ws281x-native] Could not verify raspberry-pi version.
2. error: the speech_to_text service returned an error.
Screen shot attached above

Thanks 
Divya

**Comment by victordibia** [comment]
Hi divya.. this is a fairly new issue and I have seen two of these reports
in the last two days. It's either as a result of an update to the pi is or
to the wx281 library. I see you have filed an issue with the wx281 library.
I'll do some tests of my own and also keep up with that thread. Thanks.

**Comment by divya2100** [comment]
Thanks Victor!!
Could you please let me know if you could find any solution to this issue.
Also I see in wx281, people have suggested to either comment the code or add  BCM2835.
Is this a correct way?

Thanks,
Divya

**Comment by victordibia** [comment]
Hi @divya2100 

Theres been some discussion and fix on your thread ... not sure if you've seen it.
https://github.com/beyondscreen/node-rpi-ws281x-native/pull/58#issuecomment-301797531

You should be able to pull that in by removing the tjbot lib (`rm -rf node_modules`) and running `npm install`
