### ISSUE TITLE
Syntax error when running bootstrap

### ISSUE THREAD

**Issue by arlarzelere3** [ibmtjbot/tjbot#53]
I ran the boostrap script on a freshinstall of rasbian and got the following errors

bash: line 169: syntax error near unexpected token 'fi'
bash: line 169: 'fi'

This is causing the script to end early and not completing the setup process.

**Comment by victordibia** [comment]
@jweisz

**Comment by akeller** [comment]
Same issue as @arlarzelere3. Possible whitespace issue?

**Comment by tobykurien** [comment]
Seem like the command in the README file is not using bash. Try ```curl -sL https://raw.githubusercontent.com/ibmtjbot/tjbot/master/bootstrap/bootstrap.sh > bootstrap.sh``` and then ```sudo bash ./bootstrap.sh```
