### ISSUE TITLE
Tweets

### ISSUE THREAD

**Issue by ghost** [ibmtjbot/tjbot#54]
After running "Sudo node sentiment.js",its showing

"**Not enough tweets collected to perform sentiment analysis**"

I tried changing the "exports.sentiment.keyword" but same issue persisted.

**Comment by victordibia** [comment]
@sarthak50 
I'd suggest trying a keyword with large tweet content .. just to be perfectly sure.
What keyword did you try?

-V.

**Comment by sarthak50** [comment]
I tried.Now its running but always showing the same sentiment(**JOY**)
