### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by tobykurien** [ibmtjbot/tjbot#6]
Please add the wiring diagram for the LED and the servo to this repo. I know that the Instructable has wiring for the LED but I don't see the wiring for the servo motor. Also it would be great not to have to hunt for these in Instructables, but rather have them right here. Thanks!

**Comment by victordibia** [comment]
Hi @tobykurien ,
Thanks for pointing this out. The original set of recipes in this repo do not utilize a servo hence the missing diagrams. In the mean time, I'm working on a servo recipe, and diagrams can be found there ..
https://github.com/victordibia/tjwave
![tjwave_bb](https://cloud.githubusercontent.com/assets/1547007/20632584/aebd12ac-b30c-11e6-8fa9-fb7d661900ab.jpg)
