### ISSUE TITLE
Large latancy about 7-9 seconds

### ISSUE THREAD

**Issue by djanchino** [ibmtjbot/tjbot#61]
Hi,

When i run conversation.js code all run correctly but i get big latency (in average 7 sec.). How can reduce the latency of TJBot?

Thanks.

**Comment by victordibia** [comment]
Hi @djanchino,

From my tests latency is usually between 300ms to 1200ms.
I would say you test with a different internet connection (perhaps you tether tjbot to your phone).
Also I have learned that for some users outside the US, latency tends to be slightly more (a few more seconds).

-V.
