### ISSUE TITLE
making the new workspace in IBM conversation service

### ISSUE THREAD

**Issue by NkosanaN** [ibmtjbot/tjbot#66]
hi everyone 
i have design the new conversation using IBM conversation service for TJBOT but when i copy workspace id along with downloaded json file and replace the default one coming with TJ,it's doesn't work TJBOT  experience time out error any suggestion.
and also how can i combine conversation code with sentiment code.
finale how can i make the TJBOT code to run the moment i turn on my Raspberry pi3 without executing the script manually in cmd.
i'm in need of the above information my-email addr: nkosana.prince.ndlela@gmail.com

**Comment by victordibia** [comment]
Hi @NkosanaN ,

- Its always useful to post the errors log you encounter (i.e the exact time out error logs).
- Please see the [sentiment analysis sample](https://github.com/ibmtjbot/tjbot/tree/master/recipes/sentiment_analysis) we provide to learn more about how that works.
- There is some direction on how to run a script on startup on a raspberry pi [here](https://raspberrypi.stackexchange.com/questions/8734/execute-script-on-start-up).
