### ISSUE TITLE
Speech to Text bad listening

### ISSUE THREAD

**Issue by mimoraes** [ibmtjbot/tjbot#67]
Works only using curl, nodered, but this tjbot isn't working.. 

The words aren't paraphrasing right. What should I do?

pi@Rose:/Desktop/tjbot/recipes/speech_to_text $ node stt.js
verbose: TJBot initializing LED
[rpi-ws281x-native] This module requires being run with root-privileges. A non-functional stub of the interface will be returned.
verbose: TJBot initializing microphone
verbose: TJBot initializing speech_to_text service
info: Hello from TJBot! My name is Watson.
verbose: TJBot library version v1.3.0
I understand lots of colors.  You can tell me to shine my light a different color by saying 'turn the light red' or 'change the light to green' or 'turn the light off'.
verbose: TJBot initializing microphone
**_info: TJBot heard: a 
info: TJBot heard: no 
info: TJBot heard: the 
info: TJBot heard: I'm 
info: TJBot heard: but 
info: TJBot heard: I_** 
^Cpi@Rose:/Desktop/tjbot/recipes/speech_to_text $

**Comment by mimoraes** [comment]
^Cpi@Rose:~/Desktop/tjbot/recipes/speech_to_text $ node stt.js
verbose: TJBot initializing LED
[rpi-ws281x-native] This module requires being run with root-privileges. A non-functional stub of the interface will be returned.
verbose: TJBot initializing microphone
verbose: TJBot initializing speech_to_text service
info: Hello from TJBot! My name is Watson.
verbose: TJBot library version v1.3.0
I understand lots of colors.  You can tell me to shine my light a different color by saying 'turn the light red' or 'change the light to green' or 'turn the light off'.
verbose: TJBot initializing microphone
info: TJBot heard: a 
info: TJBot heard: no 
info: TJBot heard: the 
info: TJBot heard: I'm 
info: TJBot heard: but 
info: TJBot heard: I 
^Cpi@Rose:~/Desktop/tjbot/recipes/speech_to_text $

**Comment by victordibia** [comment]
This sometimes occurs in noise environments or if the microphone quality is not good.
Generally, things like accents, background/ambient noise, and microphone quality affect the quality of transcripts.

**Comment by mimoraes** [comment]
but on translator.google.com works perfect, I don't think it is MIC/voice quality

**Comment by mimoraes** [comment]
I had to change to portuguese
