### ISSUE TITLE
adapt tjbot.listen

### ISSUE THREAD

**Issue by GuiJordao21** [ibmtjbot/tjbot#71]
Can I adapt .listen() method to listen to only one sentence?? I've been trying to do this, but it's really confusing. thx!

**Comment by victordibia** [comment]
Hi,

Can you provide more details on your use case? E.g you would like a response to only "some" commands? It is common to monitor transcripts for an  attention word and only respond when this word is uttered.

-V.

**Comment by jweisz** [comment]
`tj.listen()` is meant to provide a continuous transcript each time a new utterance is detected. If you want to stop listening after one sentence is detected, you may call `tj.stopListen()`.
