### ISSUE TITLE
Allow initialization of conversation context

### ISSUE THREAD

**Issue by bagchisu** [ibmtjbot/tjbot#73]
There doesn't appear to be a way to specify context parameters to the conversation service via TJBot. This is necessary if the conversation requires initialization via context parameters, e.g. credentials for IBM Cloud Function actions that will be called from the conversation dialog.

**Comment by victordibia** [comment]
Thanks for the note.

At the moment, you do have direct access to the conversation instance from the tjbotlibrary. 
Please see the tjbotlib documentation for how to access this - [https://github.com/ibmtjbot/tjbotlib#api-methods](https://github.com/ibmtjbot/tjbotlib#api-methods)

More sophisticated users can directly modify context parameters.

-V.
