### ISSUE TITLE
No Text to speech Recipe

### ISSUE THREAD

**Issue by mertimaxi** [ibmtjbot/tjbot#76]
Hello,

i am searching for the text to speech recipe to build a conversation with tjbot but there isn't any. Can anyone please help me?

thank you very much

**Comment by victordibia** [comment]
Hi,

We have a recipe for building a conversation with TJBot!

The code is found here- [https://github.com/ibmtjbot/tjbot/tree/master/recipes/conversation](https://github.com/ibmtjbot/tjbot/tree/master/recipes/conversation)

There is also a step by step instruction here - [http://www.instructables.com/id/Build-a-Talking-Robot-With-Watson-and-Raspberry-Pi/](http://www.instructables.com/id/Build-a-Talking-Robot-With-Watson-and-Raspberry-Pi/)

-V.
