### ISSUE TITLE
Error when running stt.js 

### ISSUE THREAD

**Issue by jammydodgegg** [ibmtjbot/tjbot#87]
Hi there,

I have just set up my raspberry pi for the speech to text program. Followed all the instructions to the letter but when I try and run it with the command ‘sudo node stt.js’ I just get an error. Please help as I don’t know how to fix this.

Please see my screenshots below. Two different errors come up 

![f922ba2f-34a7-4691-9901-7f5b4749a12d](https://user-images.githubusercontent.com/39060011/39709753-a2e7f7f2-5212-11e8-8df7-946de42146cd.jpeg)
![e4fd10af-47e3-48c7-850b-ded17730380b](https://user-images.githubusercontent.com/39060011/39709754-a31a5cec-5212-11e8-9c0d-41c97088062d.jpeg)

**Comment by victordibia** [comment]
hi @jammydodgegg 

For the first issue, you do need to have the file `config.js` (containing your credentials) in your speech to text directory. The instruction contains a step to create this file.

![image](https://user-images.githubusercontent.com/1547007/39710203-1f6b60bc-51ea-11e8-8651-06bc395a327a.png)

For the second error, you need to be in the speech to text directory  before running node stt.js. You are currently in the `/home/pi/stt.js`
